version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bookit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bookit
    ports:
      - "5432:5432"